/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mathijs' at '11/9/15 3:34 PM' with Gradle 2.7
 *
 * @author mathijs, @date 11/9/15 3:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
